name: build

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  actions: write

jobs:
  build:
    runs-on: windows-latest

    outputs:
      artifact-name: nopcommerce-build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: nuget-

      - name: Restore
        run: dotnet restore src/NopCommerce.sln

      - name: Build
        run: dotnet build src/NopCommerce.sln --configuration Release --no-restore

      - name: Publish Nop.Web
        run: dotnet publish src/Presentation/Nop.Web/Nop.Web.csproj -c Release -o publish --no-restore

      - name: Compress publish
        shell: pwsh
        run: |
          Compress-Archive `
          -Path publish\* `
          -DestinationPath nopcommerce.zip

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: nopcommerce-build
          path: nopcommerce.zip
          retention-days: 1
