name: deploy

on:
  workflow_run:
    workflows:
      - build
    types:
      - completed

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: build.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: nopcommerce-build
          path: publish

      - name: Extract artifact
        shell: pwsh
        run: |
          Expand-Archive publish/nopcommerce.zip publish

      - name: Deploy to Azure Web App
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.AZURE_FTP_SERVER }}
          protocol: ftps
          security: loose
          username: ${{ secrets.AZURE_FTP_USERNAME }}
          password: ${{ secrets.AZURE_FTP_PASSWORD }}
          local-dir: publish/
          server-dir: /site/wwwroot/
